name: 'Setup Toolkit'
description: 'Setup GitHub Actions Toolkit in your repository'

inputs:
  modules:
    description: 'Modules to setup (comma-separated)'
    required: true
    default: 'all'
  config_dir:
    description: 'Directory to store configuration files'
    required: false
    default: '.github'
  workflow_dir:
    description: 'Directory to store workflow files'
    required: false
    default: '.github/workflows'

runs:
  using: 'composite'
  steps:
    - name: Make script executable
      shell: bash
      run: chmod +x "${{ github.action_path }}/setup.sh"

    - name: Run Setup Script
      shell: bash
      run: |
        "${{ github.action_path }}/setup.sh" \
          "${{ inputs.modules }}" \
          "${{ inputs.config_dir }}" \
          "${{ inputs.workflow_dir }}"
