name: 'Test Runner'
description: 'Smart test execution with caching, coverage, and reporting'
inputs:
  framework:
    description: 'Testing framework (jest, pytest, go, vitest, ava, nose)'
    required: true
  command:
    description: 'Custom test command (overrides default)'
    required: false
  directories:
    description: 'Directories to test (comma-separated)'
    required: false
    default: '.'
  parallel:
    description: 'Number of parallel processes'
    required: false
    default: 'auto'
  cache:
    description: 'Enable test result caching'
    required: false
    default: 'true'
  pattern:
    description: 'Test pattern'
    required: false
  retry:
    description: 'Retry attempts on failure'
    required: false
    default: '1'
  openai_api_key:
    description: 'Optional OpenAI API key for AI analysis'
    required: false
outputs:
  time:
    description: 'Total execution time'
  coverage:
    description: 'Coverage percentage'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.framework }}
    - ${{ inputs.command }}
    - ${{ inputs.directories }}
    - ${{ inputs.parallel }}
    - ${{ inputs.cache }}
    - ${{ inputs.pattern }}
    - ${{ inputs.retry }}
    - ${{ inputs.openai_api_key }}
