name: 'Artifact Uploader'
description: 'Uploads a specified file or directory as an artifact.'

inputs:
  name:
    description: 'Artifact name'
    required: true
  path:
    description: 'File or directory to upload'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 📦 Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
